services:
  - type: web
    name: crimsonhub-auth
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: DISCORD_CLIENT_SECRET
        sync: false
      - key: DISCORD_REDIRECT_URI
        value: https://crimsonhub-f52q.onrender.com/callback
      - key: REQUIRED_GUILD_ID
        sync: false
      - key: PORT
        value: 3000
